# https://aka.ms/yaml
name: $(Build.DefinitionName)_$(GitVersion_InformationalVersion)

variables:
  ArtifactName: Modules

resources:
  repositories:
  - repository: templates
    endpoint: PoshCode
    type: github
    name: PoshCode/Azure-Pipelines
    ref: refs/tags/1.1.2

jobs:
  - template: GitVersion-job.yml@templates

  - job: Build
    pool:
      vmImage: 'windows-2019'
    dependsOn: GitVersion
    variables:
      InformationalVersion: $[dependencies.GitVersion.outputs['GitVersion.InformationalVersion']]

    steps:
    - template: InstallRequiredModules-step.yml@templates
      parameters:
        Destination: $(Build.SourcesDirectory)/RequiredModules

    - pwsh: ./build.ps1 -OutputDirectory $(Build.BinariesDirectory)/$(Build.DefinitionName) -SemVer $(InformationalVersion) -Verbose
      displayName: 'Run build script'

    - task: PublishPipelineArtifact@0
      displayName: 'Publish Build Output'
      inputs:
        ArtifactName: $(ArtifactName)
        targetPath: '$(Build.BinariesDirectory)'

  - template: ScriptAnalyzer-job.yml@templates
    parameters:
      dependsOn: ['Build']
      artifactName: $(ArtifactName)

  - template: Pester-job.yml@templates
    parameters:
      dependsOn: ['Build']
      artifactName: $(ArtifactName)
      TestsDirectory: '$(Build.SourcesDirectory)/Tests'
