# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(Build.DefinitionName)_$(GitVersion_InformationalVersion)

variables:
  ArtifactName: Modules

resources:
  repositories:
    - repository: templates
      type: github
      name: PoshCode/Azure-Pipelines
      ref: refs/tags/1.0.0

pool:
  vmImage: 'windows-2019' # other options include: 'Ubuntu 16.04', 'macOS 10.13', 'VS2017-Win2016'

jobs:
  - template: GitVersion-job.yml@templates

  - job: Build
    dependsOn: GitVersion
    variables:
      InformationalVersion: $[dependencies.GitVersion.outputs['GitVersion.InformationalVersion']]
    steps:
    - template: InstallRequiredModules-step.yml@templates
      displayName: 'Restore pre-requisites from RequiredModules.psd1'

    - powershell: .\build.ps1 -OutputDirectory $(Build.BinariesDirectory)\$(Build.DefinitionName) -SemVer $(InformationalVersion) -Verbose
      displayName: 'Run build script'

    - task: PublishPipelineArtifact@0
      displayName: 'Publish Build Output'
      inputs:
        ArtifactName: $(ArtifactName)
        targetPath: '$(Build.BinariesDirectory)'

  - template: ScriptAnalyzer-job.yml@templates
    parameters:
      dependsOn: ['Build']
      artifactName: $(ArtifactName)

  - template: Pester-job.yml@templates
    parameters:
      dependsOn: ['Build']
      artifactName: $(ArtifactName)
      TestsDirectory: '$(Build.SourcesDirectory)\Tests'