# https://aka.ms/yaml
name: $(GitVersion_InformationalVersion)

variables:
  ArtifactName: Modules

resources:
  repositories:
  - repository: templates
    endpoint: PoshCode
    type: github
    name: PoshCode/Azure-Pipelines
    ref: refs/tags/2.0.0

jobs:
  - template: GitVersion-job.yml@templates

  - template: Build-Module-job.yml@templates
    parameters:
      dependsOn: ['Build']
      artifactName: $(ArtifactName)

  - template: ScriptAnalyzer-job.yml@templates
    parameters:
      dependsOn: ['Build']
      artifactName: $(ArtifactName)

  - template: Pester-job.yml@templates
    parameters:
      dependsOn: ['Build']
      artifactName: $(ArtifactName)
      TestsDirectory: '$(Build.SourcesDirectory)/Tests'
